"""Remove groups from Games

Revision ID: 4207f6714223
Revises: 7f5d48031be2
Create Date: 2024-12-07 15:54:19.552981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4207f6714223'
down_revision = '7f5d48031be2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games_groups')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games_groups',
    sa.Column('game_id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['Games.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['Groups.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'group_id')
    )
    # ### end Alembic commands ###
