"""add name to Review

Revision ID: 752829ba2a7a
Revises: b98ac7fbfc40
Create Date: 2024-12-03 14:04:22.033176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752829ba2a7a'
down_revision = 'b98ac7fbfc40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Review', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
