"""create user_group table

Revision ID: 759f8c8c792d
Revises: 2bdb36bf9278
Create Date: 2024-11-27 20:57:43.934198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759f8c8c792d'
down_revision = '2bdb36bf9278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_group',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['Groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['UserInfo.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_group')
    # ### end Alembic commands ###
