"""add user_msg

Revision ID: 7f5d48031be2
Revises: ea7ccad6bd26
Create Date: 2024-12-06 11:46:14.957770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f5d48031be2'
down_revision = 'ea7ccad6bd26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=True),
    sa.Column('like', sa.Integer(), nullable=True),
    sa.Column('dislike', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['Groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_msg',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['Messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['UserInfo.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'message_id')
    )
    op.drop_table('Messsages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Messsages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=200), nullable=True),
    sa.Column('like', sa.INTEGER(), nullable=True),
    sa.Column('dislike', sa.INTEGER(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['Groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_msg')
    op.drop_table('Messages')
    # ### end Alembic commands ###
