"""remove desc from Groups

Revision ID: 9e9bf741a3f2
Revises: 70996c0d01de
Create Date: 2024-12-10 11:55:24.966584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9bf741a3f2'
down_revision = '70996c0d01de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Groups', schema=None) as batch_op:
        batch_op.drop_column('desc')

    # ### end Alembic commands ###
