"""add Review

Revision ID: b98ac7fbfc40
Revises: c7c9495909b3
Create Date: 2024-12-03 10:35:01.785138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b98ac7fbfc40'
down_revision = 'c7c9495909b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(length=100), nullable=True))
        batch_op.drop_column('review')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('text')

    # ### end Alembic commands ###
