"""Remove rating from Games model

Revision ID: c7c9495909b3
Revises: 6913def837ef
Create Date: 2024-12-03 10:33:28.299905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c9495909b3'
down_revision = '6913def837ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review', sa.String(length=100), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['Games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Games', schema=None) as batch_op:
        batch_op.drop_column('review')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('review', sa.VARCHAR(length=100), nullable=True))

    op.drop_table('Review')
    # ### end Alembic commands ###
