"""add games to Groups

Revision ID: ea7ccad6bd26
Revises: 752829ba2a7a
Create Date: 2024-12-04 14:58:16.484418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea7ccad6bd26'
down_revision = '752829ba2a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games_groups',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['Games.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['Groups.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games_groups')
    # ### end Alembic commands ###
